// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/szykes/go-unit-test/iam (interfaces: identityProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock/iam_mock.go -package=mock . identityProvider
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	user "github.com/szykes/go-unit-test/user"
	gomock "go.uber.org/mock/gomock"
)

// MockidentityProvider is a mock of identityProvider interface.
type MockidentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockidentityProviderMockRecorder
	isgomock struct{}
}

// MockidentityProviderMockRecorder is the mock recorder for MockidentityProvider.
type MockidentityProviderMockRecorder struct {
	mock *MockidentityProvider
}

// NewMockidentityProvider creates a new mock instance.
func NewMockidentityProvider(ctrl *gomock.Controller) *MockidentityProvider {
	mock := &MockidentityProvider{ctrl: ctrl}
	mock.recorder = &MockidentityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidentityProvider) EXPECT() *MockidentityProviderMockRecorder {
	return m.recorder
}

// FetchUser mocks base method.
func (m *MockidentityProvider) FetchUser(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUser", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUser indicates an expected call of FetchUser.
func (mr *MockidentityProviderMockRecorder) FetchUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUser", reflect.TypeOf((*MockidentityProvider)(nil).FetchUser), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockidentityProvider) ListUsers(ctx context.Context) ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockidentityProviderMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockidentityProvider)(nil).ListUsers), ctx)
}
