// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/szykes/go-unit-test/iam (interfaces: idper)
//
// Generated by this command:
//
//	mockgen -destination=mock/iam_mock.go -package=mock . idper
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	user "github.com/szykes/go-unit-test/user"
	gomock "go.uber.org/mock/gomock"
)

// Mockidper is a mock of idper interface.
type Mockidper struct {
	ctrl     *gomock.Controller
	recorder *MockidperMockRecorder
	isgomock struct{}
}

// MockidperMockRecorder is the mock recorder for Mockidper.
type MockidperMockRecorder struct {
	mock *Mockidper
}

// NewMockidper creates a new mock instance.
func NewMockidper(ctrl *gomock.Controller) *Mockidper {
	mock := &Mockidper{ctrl: ctrl}
	mock.recorder = &MockidperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockidper) EXPECT() *MockidperMockRecorder {
	return m.recorder
}

// FetchUser mocks base method.
func (m *Mockidper) FetchUser(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUser", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUser indicates an expected call of FetchUser.
func (mr *MockidperMockRecorder) FetchUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUser", reflect.TypeOf((*Mockidper)(nil).FetchUser), ctx, userID)
}

// ListUsers mocks base method.
func (m *Mockidper) ListUsers(ctx context.Context) ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockidperMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*Mockidper)(nil).ListUsers), ctx)
}
